name: Anatomy of a GitHub Actions Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      some_name:
        description: 'Some description'
        required: true
        default: 'Some default value'
        type: string
      your_env:
        description: 'Your environment'
        required: true
        default: 'DEV'
        type: choice
        options:
          - 'DEV'
          - 'PROD'
      do_deploy:
        description: 'Do deploy'
        required: true
        type: boolean

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    permissions:
        contents: read
        pull-requests: write
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!

  deploy:
    needs: build
    permissions:
        contents: read
        pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
