name: group_a

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2
      - name: Build with Tests
        run: ./gradlew build --continue -s
        env:
          REGISTRY_PAT: ${{ github.token }}

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: list files
        run: |
          ls -trl
      - name: deploy (mock)
        run: |
          if [ ! -f demo-0.0.1-SNAPSHOT.jar ]; then
            echo "File does not exist"
            exit 1
          fi
