name: team_b_1

on:
  workflow_dispatch:

jobs:
  print-plaintext:
    runs-on: ubuntu-22.04
    environment: fortknox
    steps:
      - name: Print out the treasure
        shell: bash
        run: |
          echo The secret: ${{ secrets.TREASURE }}
      - name: Verify Task
        shell: bash
        run: |
          : "${{ secrets.TREASURE:?TREASURE is not set or is empty }}"

  print-hash:
    runs-on: ubuntu-22.04
    environment: fortknox
    needs: print-plaintext
    steps:
      - name: Print out the treasure
        shell: bash
        run: |
          echo The secret as hash: `openssl passwd -1 ${{ secrets.TREASURE }}`
